blank/urls.py
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'), #url per la pagina index
    #path('process/', views.process_smiles, name='process_smiles'), #url per process smiles
    path('salva_smiles/', views.salva_smiles, name='salva_smiles'),
]
"""
#blank/urls

from django.urls import path
from . import views

app_name = 'blank'  # Aggiungi questa riga!

urlpatterns = [
    path('', views.index, name='index'),  # URL per il form
    path('results/', views.process_smiles, name='process_smiles'),  # URL per la view di processamento e risultati
]    

blank_template/urls.py
#blank_template/urls

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blank.sitemaps import TestBioSitemap  # Importa da blank.sitemaps



sitemaps = {
    'testbio': TestBioSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blank.urls')),  # Includi le URL dell'app blank
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Aggiungi il pattern per servire i file media
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blank/models.py
from django.db import models

class YourModelName(models.Model):
    # Existing model fields ...
    bioactivity = models.TextField(max_length=1024, blank=True)  # Adjust max_length as needed
# Create your models here.

blank/forms.py
 # blank/forms.py


from django import forms

class SmilesForm(forms.Form):
    smiles_input = forms.CharField(widget=forms.Textarea(attrs={'rows': 15, 'cols': 80}), label="Insert SMILES (one per line):")

blank/views.py
  
#blank/views

import numpy as np
import os
import pandas as pd
from django.shortcuts import render
from django.http import HttpResponse
from .forms import SmilesForm
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
from rdkit import Chem
import matplotlib.pyplot as plt
import networkx as nx
import seaborn as sns
from django.conf import settings
import base64
from io import BytesIO



############

def genera_grafico_base64(fig, format='png'):
    """Converte una figura matplotlib in base64."""
    buf = BytesIO()
    fig.savefig(buf, format=format)
    buf.seek(0)
    string = base64.b64encode(buf.read())
    return string.decode('utf-8')


def genera_scatterplot(df):
    try:
        if 'query_index' in df.columns and 'library_index' in df.columns:
            plt.figure(figsize=(10, 6))
            plt.scatter(df['query_index'], df['library_index'])
            plt.title('Scatterplot')
            plt.xlabel('Phytocomplex Index')
            plt.ylabel('Library Index')
            plt.tight_layout()

            fig = plt.gcf()  # Ottieni la figura corrente
            scatterplot_base64 = genera_grafico_base64(fig)  # Codifica in base64 PRIMA di chiudere la figura

            plt.close(fig)  # Chiudi la figura per liberare memoria
            return scatterplot_base64
        else:
            return "Colonne 'query_index' o 'library_index' non presenti."
    except Exception as e:
        return f"Errore nello scatterplot: {e}"







def genera_barplot(df):
    try:
        if 'target' in df.columns:
            target_counts = df['target'].value_counts()
            plt.figure(figsize=(12, 8))

            # Assegna x a hue e imposta legend=False
            sns.barplot(x=target_counts.index[:20], y=target_counts.values[:20], hue=target_counts.index[:20], palette="crest", legend=False)

            plt.title('Target Frequency (Top 20)')
            plt.xlabel('Target')
            plt.ylabel('Frequency')
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()
            fig = plt.gcf()
            barplot_base64 = genera_grafico_base64(fig)
            plt.close(fig)
            return barplot_base64
        else:
            return "Colonna 'target' non presente."
    except Exception as e:
        return f"Errore nel barplot: {e}"

def genera_boxplot(df):
    try:
        if 'target' in df.columns and 'similarity' in df.columns:
            target_counts = df['target'].value_counts()
            plt.figure(figsize=(12, 8))
            sns.boxplot(x='target', y='similarity', data=df[df['target'].isin(target_counts.index[:10])])
            plt.title('Boxplot of Similarity by Target (Top 10)')
            plt.xlabel('Target')
            plt.ylabel('Tanimoto coefficient')
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()
            fig = plt.gcf()
            boxplot_base64 = genera_grafico_base64(fig)
            plt.close(fig)
            return boxplot_base64
        else:
            return "Colonne 'target' o 'similarity' non presenti."
    except Exception as e:
        return f"Errore nel boxplot: {e}"



def genera_network_graph(df, tanimoto_threshold=0.3, font_size=12, node_size=100):
    try:
        if not df.empty and 'similarity' in df.columns and 'query_index' in df.columns and 'target' in df.columns:
            G = nx.Graph()
            for index, row in df.iterrows():
                tanimoto = row['similarity']
                if tanimoto is not None and tanimoto >= tanimoto_threshold:
                    G.add_edge(row['query_index'], row['target'], weight=tanimoto)

            if G.number_of_edges() > 0:
                plt.figure(figsize=(15, 10))

                # Layout a due colonne
                left_nodes = set(df['query_index'].unique())
                right_nodes = set(df['target'].unique())
                pos = {}

                # Posiziona i nodi sulla sinistra e sulla destra
                y_left = 0
                for node in left_nodes:
                    pos[node] = (-1, y_left)
                    y_left += 1

                y_right = 0
                for node in right_nodes:
                    pos[node] = (1, y_right)
                    y_right += 1

                nx.draw(G, pos, 
                        with_labels=True, 
                        node_size=node_size, 
                        font_size=font_size, 
                        width=[G[u][v]['weight'] * 3 if 'weight' in G[u][v] else 1 for u, v in G.edges()],
                        edge_color="gray", 
                        alpha=0.7,
                        node_color="skyblue")

                plt.title(f'Network graph (Relazioni tra Fitocomplessi e Target) - Tanimoto >= {tanimoto_threshold}')
                plt.tight_layout()
                fig = plt.gcf()
                network_graph_base64 = genera_grafico_base64(fig)
                plt.close(fig)
                return network_graph_base64
            else:
                return "Nessuna connessione trovata con la soglia di Tanimoto specificata."
        else:
            return "DataFrame vuoto o colonne necessarie mancanti. Impossibile generare il network graph."
    except Exception as e:
        return f"Errore nella generazione del network graph: {e}"



"""
def genera_network_graph(df, tanimoto_threshold=0.3, font_size=12, node_size=100):
    try:
        # ... (codice precedente)

        if G.number_of_edges() > 0:
            plt.figure(figsize=(20, 15))  # Aumenta le dimensioni del grafico
            pos = nx.spring_layout(G, k=0.3)  # Prova un layout diverso, ad esempio nx.kamada_kawai_layout
            nx.draw(G, pos, 
                    with_labels=True, 
                    node_size=node_size * 2,  # Aumenta la dimensione dei nodi
                    font_size=font_size, 
                    width=[G[u][v]['weight'] * 3 if 'weight' in G[u][v] else 1 for u, v in G.edges()],
                    edge_color="gray", 
                    alpha=0.7,
                    node_color="skyblue")  # Aggiungi colore ai nodi

            plt.title(f'Grafico Network (Relazioni tra Fitocomplessi e Target) - Tanimoto >= {tanimoto_threshold}')
            plt.tight_layout()
            fig = plt.gcf()
            network_graph_base64 = genera_grafico_base64(fig)
            plt.close(fig)
            return network_graph_base64
        else:
            return "Nessuna connessione trovata con la soglia di Tanimoto specificata."
        # ... (codice precedente)
    except Exception as e:
        return f"Errore nella generazione del network graph: {e}"







def genera_network_graph(df, tanimoto_threshold=0.3, font_size=12, node_size=100):
    try:
        if not df.empty and 'similarity' in df.columns and 'query_index' in df.columns and 'target' in df.columns:
            G = nx.Graph()
            for index, row in df.iterrows():
                tanimoto = row['similarity']
                if tanimoto is not None and tanimoto >= tanimoto_threshold:
                    G.add_edge(row['query_index'], row['target'], weight=tanimoto)

            if G.number_of_edges() > 0:
                plt.figure(figsize=(15, 10))
                pos = nx.spring_layout(G, k=0.3)
                nx.draw(G, pos, with_labels=True, node_size=node_size, font_size=font_size,
                        width=[G[u][v]['weight'] * 3 if 'weight' in G[u][v] else 1 for u, v in G.edges()],
                        edge_color="gray", alpha=0.7)
                plt.title(f'Grafico Network (Relazioni tra Fitocomplessi e Target) - Tanimoto >= {tanimoto_threshold}')
                plt.tight_layout()
                fig = plt.gcf()
                network_graph_base64 = genera_grafico_base64(fig)
                plt.close(fig)
                return network_graph_base64
            else:
                return "Nessuna connessione trovata con la soglia di Tanimoto specificata."
        else:
            return "DataFrame vuoto o colonne necessarie mancanti. Impossibile generare il network graph."
    except Exception as e:
        return f"Errore nella generazione del network graph: {e}"

"""


#############
def load_library_data(fingerprint_file, target_file, bioactivity_file):
    """Carica fingerprint e target da file."""
    try:
        with open(fingerprint_file, 'r') as f_fp, open(target_file, 'r') as f_t, open(bioactivity_file, 'r') as f_b:
            library_fingerprints = {}
            library_targets = {}
            library_bioactivities = {}  # Nuovo dizionario per le bioattività
            for i, (fp_line, target_line, bioactivity_line) in enumerate(zip(f_fp, f_t, f_b)):

                fp_line = fp_line.strip()
                target = target_line.strip()
                bioactivity = bioactivity_line.strip()
                library_bioactivities[i] = bioactivity  # Aggiungi bioattività
                if not fp_line:
                    continue
                fingerprint = [int(bit) for bit in fp_line.split(';')]
                library_fingerprints[i] = fingerprint
                library_targets[i] = target
        return library_fingerprints, library_targets, library_bioactivities
    except FileNotFoundError:
        return None, None
    except ValueError:
        return None, None


def salva_smiles(request):
    if request.method == 'POST':
        form = SmilesForm(request.POST)
        if form.is_valid():
            smiles_input = form.cleaned_data['smiles_input']
            smiles_list = smiles_input.strip().splitlines()

            fingerprints = calculate_fingerprints(smiles_list)  # Chiamata a calculate_fingerprints

            context = {
                'smiles_list': smiles_list,
                'fingerprints': fingerprints,
            }
            return render(request, 'results.html', context)
        else:
            return render(request, 'index.html', {'form': form})
    else:
        return render(request, 'index.html')

blank/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Python blank template{% endblock %}</title>
    
    <meta name="google-site-verification" content="pOQEzargCO0_XvIxo1hGdlKD78lWgY3pgb-hH0AErjo" />
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>

    <div class="fixed-bottom d-flex justify-content-end mb-3 mr-3">  <a href="{% static 'tutorials/tutorial.pdf' %}" class="btn btn-primary" target="_blank">
            <i class="fas fa-download mr-2"></i> Tutorial (PDF)
        </a>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/your_font_awesome_kit_id.js" crossorigin="anonymous"></script>  {% block scripts %}
    {% endblock %}
</body>

</html>

blank/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>testbio</h1>
    <form method="post" action="{% url 'blank:process_smiles' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">processes molecules (takes a few minutes)</button>
    </form>

    {% include "presentazione.html" %}  {# Includi qui la pagina di presentazione #}
{% endblock %}

blank/templates/presentazione.html
{% extends "base.html" %}  {# Eredita da base.html, IMPORTANTE! #}

{% block title %}
    <title>Presentazione del sito</title>
{% endblock %}

{% block content %}  {# Assicurati che il blocco content sia aperto e chiuso correttamente #}
    <h1>Welcome to testbio: a tool for estimating the bioactivity of phytocomplexes (mixtures of compounds found in plant material).</h1>

    <p>
   

Researchers studying medicinal plants often face the challenge of understanding the combined effects of the many different compounds present in plant extracts.  Predicting the bioactivity of these complex mixtures, known as phytocomplexes, can be time-consuming and expensive. TestBio offers a solution by providing a rapid, in silico method for estimating the potential bioactivity of a phytocomplex.  By comparing the molecular structures of the phytocomplex components to a library of known bioactive compounds, TestBio identifies potential targets and suggests possible bioactivities, accelerating the research process and guiding further investigation.  This tool is valuable for anyone working with plant extracts, from academic researchers to those in the nutraceutical and pharmaceutical industries.   
On this site, you can predict the biological activity of the compounds found in a plant species.


By entering the molecules from a botanical species in the appropriate text area in SMILES format, one per line, you will obtain a dataset of information that will be analyzed with four types of graphs.

How this tool works: The molecules provided to this tool are processed by calculating their fingerprints, which are then compared against a library of 1,700 compounds with known biological activity and protein targets. These targets are the receptor proteins within the human body that the compounds bind to in order to produce a biological effect.

The fingerprint comparison is performed using the Tanimoto coefficient. This returns a value between zero and one, where 1 represents identity. Each molecule processed is compared against every compound in the library, returning a ranking of the compounds with the highest similarity. This produces a DataFrame containing the similarity scores, target information, and bioactivities for each comparison.


    </p>

   The dataset is analyzed with four types of graphs:


Scatter Plot: Generates a scatter plot to visualize the distribution of Tanimoto similarity scores for each compound in the phytocomplex.


Bar Chart: Creates a bar chart to show the frequency of different protein targets associated with the compounds.


Box Plot: Generates a box plot to analyze the distribution of Tanimoto similarity scores across different targets.


Network Visualization: Constructs a network visualization to depict the interactions between compounds in the phytocomplex and potential target molecules.


Overall, the code effectively utilizes Python libraries such as pandas, RDKit, matplotlib, and plotly to perform data manipulation, fingerprint analysis, and various visualizations.
This  tool is for research purposes only and not for medical advice.



    <p>
       

    <p>
      For further information, please consult the tutorial and send any inquiries to the email address: 
      <a href="mailto:alessandrocareglio@gmail.com">alessandrocareglio@gmail.com</a>
       
    </p>
{% endblock %}  {# Assicurati che il blocco content sia aperto e chiuso correttamente #}

blank/templates/results.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Biological activity estimation results</h1>

    {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}

    {% if graph_filenames %}
        <h2>Graph:</h2>

        <div style="display: flex; flex-direction: column;">  {# Contenitore PRINCIPALE in colonna #}
            {% if graph_filenames.scatter %}
                <div style="margin-bottom: 20px;"> {# Contenitore per ogni grafico #}
                    <h3>Scatterplot</h3>
                    {% if "Errore" in graph_filenames.scatter %}
                        <p style="color:red">{{ graph_filenames.scatter }}</p>
                    {% else %}
                        <img src="data:image/png;base64,{{ graph_filenames.scatter }}" alt="Scatterplot" style="max-width: 100%;">
                    {% endif %}
                </div>
            {% endif %}

            {% if graph_filenames.bar %}
                <div style="margin-bottom: 20px;">
                    <h3>Barplot</h3>
                    {% if "Errore" in graph_filenames.bar %}
                        <p style="color:red">{{ graph_filenames.bar }}</p>
                    {% else %}
                        <img src="data:image/png;base64,{{ graph_filenames.bar }}" alt="Barplot" style="max-width: 100%;">
                    {% endif %}
                </div>
            {% endif %}

            {% if graph_filenames.box %}
                <div style="margin-bottom: 20px;">
                    <h3>Boxplot</h3>
                    {% if "Errore" in graph_filenames.box %}
                        <p style="color:red">{{ graph_filenames.box }}</p>
                    {% else %}
                        <img src="data:image/png;base64,{{ graph_filenames.box }}" alt="Boxplot" style="max-width: 100%;">
                    {% endif %}
                </div>
            {% endif %}
        </div>  {# Chiusura del contenitore PRINCIPALE in colonna #}
    {% endif %}

    {% if network_graph_filename %}
        <h2> Network Graph:</h2>
        <div style="text-align: center;">
            {% if "Errore" in network_graph_filename %}
                <p style="color:red">{{ network_graph_filename }}</p>
            {% else %}
                <img src="data:image/png;base64,{{ network_graph_filename }}" alt="Network Graph" style="max-width: 90%;">
            {% endif %}
        </div>
    {% endif %}

    
    
   <script>
    console.log("Valore di comparison_results:", {{ comparison_results|safe }});
   </script> 
    
    
    
    
    {% if comparison_results %}
        <h2>Comparison Results (Tanimoto coefficient):</h2>
        <table>
            <thead>
                <tr>
                    <th>Query Index</th>
                    <th>Library Index</th>
                    <th>Tanimoto Similarity</th>
                    <th>Target</th>
                    <th>Bioactivity</th>
                </tr>
            </thead>
            <tbody>
                {% for result in comparison_results %}
               
                    <tr>
                        <td>{{ result.query_index }}</td>
                        <td>{{ result.library_index }}</td>
                        <td>{{ result.similarity|floatformat:3 }}</td>
                        <td>{{ result.target }}</td>
                        <td>{{ result.bioactivity}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <a href="{% url 'blank:index' %}">Torna al form</a>
{% endblock %}